# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

image:
  - Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet build --configuration Release --verbosity quiet
  - cmd: dotnet pack ./MockServer.Net.Client/MockServer.Net.Client.csproj --configuration Release --no-restore --no-build --verbosity quiet

test:
  assemblies:
    only:
      - MockServer.Net.Client.UnitTests\bin\Release\netcoreapp2.0\MockServer.Net.Client.UnitTests.dll

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: hUkhIXTpdjZMy2lopC8rAa2AvIHRa7hTF2M2neTrgh3FTSgxtuiGHWfl9WcTsz6+
    skip_symbols: true
    artifact: /.*\.nupkg/